dessie# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dessie DiMino
email: ddimino@caltech.edu
description: > # this means to ignore newlines until "baseurl:"
 Dessie DiMino, Caltech 2020 Computer Science Major 
 Intel Semifinalist for Research done with 3D Printed BioScaffolds
 Programmer for FIRST Tech Challenge Robotics Team the Icebreakers
 Girls Who Code Summer Immersion Program 2014

   
baseurl: "" # the subpath of your site, e.g. /blog
url: "dessie-dimino.github.io" # the base hostname & protocol for your site
twitter_username: @dessiedimino
github_username:  dessie-dimino

# Build settings
markdown: kramdown
